### ISSUE TITLE
Why Go? Why not Kotlin Native 🤔

### ISSUE THREAD

**Issue by davidgomesdev** [limwa/advent-of-code-2024#1]

**Comment by limwa** [comment]
:sweat_smile: I use AoC to get better at languages I'm not very good in: last year was Rust and it helped in better understanding the language. This year, I wanted to do the same with Go because it's been on my backlog for a while now and I'm having fun so far!

**Comment by limwa** [comment]
Plus, I've been working more and more with Kubernetes lately and operators are generally written in Go. So, if I want to contribute, I need to get better at Go

**Comment by davidgomesdev** [comment]
> Plus, I've been working more and more with Kubernetes lately and operators are generally written in Go. So, if I want to contribute, I need to get better at Go

Good point!
